[package]
name = "oxideav-hls"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MIT"
repository = "https://github.com/Robert-Hughes/oxideav-hls"
description = "HLS VOD source driver for OxideAV"

[dependencies]
log = "0.4"
oxideav-core = "0.1"
oxideav-http = "0.0.8"
oxideav-mpegts = "0.0.3"
m3u8-rs = "6.0.1"
url = "2"

[patch.crates-io]
oxideav-core = { git = "https://github.com/Robert-Hughes/oxideav-core.git", branch = "dev" }
oxideav-http = { git = "https://github.com/Robert-Hughes/oxideav-http.git", branch = "dev" }